<div class="ankitdev_request-invoice">
    <form id="custom-contact-form" class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl("requestpost/index/post")?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
        <h1><?= $block->escapeHtml(__('Reqest Invoice Form')) ?></h1>
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
            <div class="field order-id required">
                <label class="label" for="order-id"><span><?= $block->escapeHtml(__('Order ID')) ?></span></label>
                <div class="control">
                    <input name="order_id" id="order-id" class="input-text" type="number" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field customer-name required">
                <label class="label" for="customer-name"><span><?= $block->escapeHtml(__('Name of the customer')) ?></span></label>
                <div class="control">
                    <input name="name_customer" id="customer-name" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field customer-email required">
                <label class="label" for="email-customer"><span><?= $block->escapeHtml(__('Email of the customer')) ?></span></label>
                <div class="control">
                    <input name="email_customer" id="email-customer" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field customer-telephone required">
                <label class="label" for="customer-telephone"><span><?= $block->escapeHtml(__('Mobile Number of the customer')) ?></span></label>
                <div class="control">
                    <input name="telephone_customer" id="customer-telephone" class="input-text" type="number" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field company-name required">
                <label class="label" for="company-name"><span><?= $block->escapeHtml(__('Company Name')) ?></span></label>
                <div class="control">
                    <input name="company_name" id="company-name" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field company-tax-code required">
                <label class="label" for="company-tax-code"><span><?= $block->escapeHtml(__('Company Tax Code')) ?></span></label>
                <div class="control">
                    <input name="company_tax_code" id="company-tax-code" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field company-address required">
                <label class="label" for="company-address"><span><?= $block->escapeHtml(__('Company Address')) ?></span></label>
                <div class="control">
                    <textarea name="company_address" id="company-address" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" id="add" title="" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<script>
/*require(['jquery'],function($){
    $(document).ready(function(){
        $("#add").click(function(){
        var customurl = "<?php //echo $this->getUrl("requestinvoice/index/post") ?>";
        $.ajax({
            url: customurl,
            type: "POST",
            data: $(this).closest('form').serialize(),
            dataType: "json",
            showLoader: true,
            success: function(result){
                console.log(result);
            }
        });
        $('#custom-contact-form')[0].reset(); 
        return false;
        });
    });
});*/ 
</script>